#r "../node_modules/fable-core/Fable.Core.dll"
#load "CodeMirrorImports.fs"
#load "CodeMirrorInterface.fs"
#load "./Common-3/VisualMIPS/types.fs"
#load "./Common-3/VisualMIPS/datastruct.fs"
#load "./Common-3/VisualMIPS/machinecode.fs"
#load "./Common-3/VisualMIPS/tokeniser.fs"
#load "./Common-3/VisualMIPS/parser.fs"
#load "./Common-3/VisualMIPS/r_type.fs"
#load "./Common-3/VisualMIPS/i_type.fs"
#load "./Common-3/VisualMIPS/j_type.fs"
#load "./Common-3/VisualMIPS/instructer.fs"
#load "main.fs"

