#r "../node_modules/fable-core/Fable.Core.dll"
#load "CodeMirrorImports.fs"
#load "CodeMirrorInterface.fs"
#load "./Common/VisualMIPS/types.fs"
#load "./Common/VisualMIPS/datastruct.fs"
#load "./Common/VisualMIPS/tokeniser.fs"
#load "./Common/VisualMIPS/parser.fs"
#load "./Common/VisualMIPS/r_type.fs"
#load "./Common/VisualMIPS/instructer.fs"
#load "main.fs"

